version: "3.7"

services:

  building-maker:
    container_name: building-maker
    image: building-maker:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9054:9054

networks:
  default:
    name: tz1and_prod